# Generated by Django 5.1.5 on 2025-01-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="media/ratings")),
                ("description", models.TextField()),
                ("position", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Ratings",
                "verbose_name_plural": "rating",
            },
        ),
    ]
